src/IPIMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
# Haystack Search
from haystack.forms import SearchForm
from haystack.views import SearchView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'default.views.home', name='home'),
    url(r'^dashboard/$', 'default.views.doctorDashboard', name='doctordashboard'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^patient/', include('patients.urls')),
    url(r'^search/', login_required(SearchView(form_class=SearchForm))),
    url(r'^appointments/', include('appointments.urls')),
    url(r'^inbox/notifications/', include('notifications.urls', namespace="notifications")),
    url(r'^prescriptions/', include('prescriptions.urls', namespace="prescriptions")),
    url(r'^stats/', 'stats.views.statisticalAnalysis'),
    url(r'^hc/', 'stats.views.plot'),
    url(r'^labs/', include('labreports.urls', namespace = "labreports")),
    url(r'^records/', include('records.urls', namespace="records")),
]

src/patients/urls.py
   
from django.conf.urls import include, url
from django.contrib import admin
from patients import views
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^(?P<pk>[0-9]+)/$',
		login_required(views.patientProfile),
		name='patient_profile'),
	url(r'^(?P<pk>[0-9]+)/update/$',
		login_required(views.PatientUpdate.as_view()), name='patient_update_form'),
	url(r'^add/$', 
		login_required(views.PatientNew.as_view(success_url="/")), name='patient_registration_form'),
	url(r'^(?P<pk>[0-9]+)/health/$',
		login_required(views.CurrentHealthCondition.as_view()), name='patient_health_condition_form'),
]

src/labreports/models.py
from django.db import models
from patients.models import Patient
from django.contrib.auth.models import User
import datetime

class LabTest(models.Model):
	name = models.CharField(max_length = 128)
	def __str__(self):
		return self.name

# Create your models here.
class LabReport(models.Model):
	REQUESTED = 'r'
	IN_PROGRESS = 'ip'
	COMPLETE = 'c'

	STATUS_CHOICES = ((REQUESTED, 'Requested'), (IN_PROGRESS, 'In Progress'), (COMPLETE, 'Complete'))

	request_date = models.DateField(("Lab Request Date"), default=datetime.date.today)
	doctor = models.ForeignKey(User, related_name="doctor")
	patient = models.ForeignKey(Patient)
	lab_test = models.ForeignKey('LabTest')
	status = models.CharField(max_length=2, choices=STATUS_CHOICES)
	doctor_notes = models.TextField(blank=True, null=True)
	results = models.TextField(blank=True, null=True)
	lab_technician = models.ForeignKey(User, blank=True, null=True, related_name="lab_technician")
	update_date = models.DateField(("Last updated"), blank=True, null=True)

	def __str__(self):
		return 'lab_report_' + str(self.pk)

src/patients/models.py
from django.db import models

# Create your models here.
from django.utils.translation import ugettext as _
from localflavor.us.models import USStateField
from localflavor.us.models import PhoneNumberField

class MedicalBackgroundChoice(models.Model):
	description = models.CharField(max_length=128)
	def __str__(self):
		return self.description

class Allergy(models.Model):
	description = models.CharField(max_length=128)
	def __str__(self):
		return self.description

class Patient(models.Model):

	# Patient Sex Constants
	MALE = 'm'
	FEMALE = 'f'
	SEX_CHOICES = ((MALE, 'Male'), (FEMALE, 'Female'))

	# Patient Ethnicity Constansts
	WHITE = 'wh'
	BLACK = 'bl'
	NATIVE_AMERICAN = 'na'
	HISPANIC = 'hi'
	ASIAN = 'as'
	OTHER = 'o'
	ETHNICITY_CHOICES = ((WHITE, 'White'), 
						(BLACK, 'Black'), 
						(NATIVE_AMERICAN, 'Native American'), 
						(HISPANIC, 'Hispanic'),
						(ASIAN, 'Asian'),
						(OTHER, 'Other'))

	profile_picture = models.ImageField(upload_to = 'images/', blank=True, null=True)

	first_name = models.CharField(max_length = 30)
	last_name = models.CharField(max_length = 30)
	dob = models.DateField()
	sex = models.CharField(max_length=1, choices=SEX_CHOICES)
	ethnicity = models.CharField(max_length=2, choices=ETHNICITY_CHOICES)
	ssn = models.CharField(max_length = 11)
	phone_number = PhoneNumberField(default = 'null')
	email = models.EmailField(default = 'null')

	# Address Info
	address = models.CharField(max_length = 128)
	city = models.CharField(max_length=64)
	state = USStateField()
	zip_code = models.PositiveIntegerField()

	# Health Insurance
	health_insurance_provider = models.CharField(max_length = 64)
	health_insurance_id = models.CharField(max_length = 30)

	# Medical History
	medical_background_information = models.ManyToManyField(MedicalBackgroundChoice, blank=True)
	allergies = models.ManyToManyField(Allergy, blank=True)

	def get_full_name(self):
		# returns the patient's full name (ex: Doe, John)
		return '%s, %s' % (self.last_name, self.first_name)	

	def get_full_name_normalized(self):
		# returns the patient's full name (John Doe)
		return '%s %s' % (self.first_name, self.last_name)

	def get_ssn(self):
		return 'xxx-xx' + self.ssn[6:]

	DISCOMFORT_LEVELS = (('1', '1'),('2', '2'),('3', '3'),('4', '4'),('5', '5'),('6', '6'),('7', '7'),('8', '8'),('9', '9'),('10', '10'))
	nausea_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Nausea')
	headache_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Headache')
	sore_throat_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Sore throat')
	abdominal_pain_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Abdominal pain')
	constipation_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Constipation')
	lack_of_appetite_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Lack of appetite')
	sleepiness_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Sleepiness')
	insomnia_level = models.CharField(max_length=2, choices=DISCOMFORT_LEVELS, default=1, verbose_name='Insomnia')
	
	def __str__(self):
		return self.get_full_name()

src/patients/forms.py
from django.forms import ModelForm
from patients.models import Patient
from django.forms.widgets import CheckboxSelectMultiple, RadioSelect
from django.utils.safestring import mark_safe
from django import forms

from crispy_forms.helper import FormHelper, Layout

from crispy_forms.layout import Submit

# Create the form class.

class PatientRegistrationForm(ModelForm):


	class Meta:
		model = Patient
		exclude = 'nausea_level', 'headache_level', 'sore_throat_level', 'abdominal_pain_level', 'constipation_level', 'lack_of_appetite_level', 'sleepiness_level', 'insomnia_level'

		widgets = {
			'medical_background_information': CheckboxSelectMultiple,
			'allergies': CheckboxSelectMultiple
		}

	def __init__(self, *args, **kwargs):
		super(PatientRegistrationForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper(self)
		self.helper.layout.append(Submit('save', 'save'))
		self.helper.layout = Layout('name',)
			

class CurrentHealthConditionForm(ModelForm):
	def __init__(self, *args, **kwargs):
		super(CurrentHealthConditionForm, self).__init__(*args, **kwargs)
		self.fields['nausea_level'].widget = forms.HiddenInput()
		self.fields['headache_level'].widget = forms.HiddenInput()
		self.fields['sore_throat_level'].widget = forms.HiddenInput()
		self.fields['abdominal_pain_level'].widget = forms.HiddenInput()
		self.fields['constipation_level'].widget = forms.HiddenInput()
		self.fields['lack_of_appetite_level'].widget = forms.HiddenInput()
		self.fields['sleepiness_level'].widget = forms.HiddenInput()
		self.fields['insomnia_level'].widget = forms.HiddenInput()

	class Meta:
		model = Patient
		fields = 'nausea_level', 'headache_level', 'sore_throat_level', 'abdominal_pain_level', 'constipation_level', 'lack_of_appetite_level', 'sleepiness_level', 'insomnia_level'

		widgets = {
			# 'nausea_level': RadioSelect,
			# 'headache_level': RadioSelect,
			# 'sore_throat_level': RadioSelect,
			# 'abdominal_pain_level': RadioSelect,
			# 'constipation_level': RadioSelect,
			# 'lack_of_appetite_level': RadioSelect,
			# 'sleepiness_level': RadioSelect,
			# 'insomnia_level': RadioSelect,
		}

src/patients/views.py
from django.shortcuts import render, render_to_response, RequestContext
from haystack.query import SearchQuerySet
from haystack.forms import SearchForm
from .forms import PatientRegistrationForm, CurrentHealthConditionForm
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views.generic import CreateView, UpdateView, DetailView, ListView
from haystack.generic_views import SearchView
from .models import Patient

from appointments.models import Appointment
from prescriptions.models import Prescription
from labreports.models import LabReport
from records.models import Record

from notifications import notify
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect



class PatientNew(CreateView):
	model = Patient
	form_class = PatientRegistrationForm

	def get_success_url(self):
		return reverse('patient_profile', kwargs={
			'pk': self.object.pk
			})

class PatientUpdate(UpdateView):
	model = Patient
	form_class = PatientRegistrationForm
	def get_success_url(self):
		return reverse('patient_profile', kwargs={
			'pk': self.object.pk
			})

class CurrentHealthCondition(UpdateView):
	model = Patient
	template_name_suffix = '_update_form'
	form_class = CurrentHealthConditionForm

	def form_valid(self, form):
		self.object = form.save()
		calculate_health_condition(self, form)
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse('patient_profile', kwargs={
			'pk': self.object.pk
			})

def calculate_health_condition(self, form):
	user = self.request.user
	patient = self.object
	total = 0
	current_health_condition_levels = {'Nausea level': patient.nausea_level, 'Headache level': patient.headache_level, 'Sore Throat level': patient.sore_throat_level, 'Abdominal Pain level': patient.abdominal_pain_level, 'Constipation level': patient.constipation_level, 'Lack of Appetite level': patient.lack_of_appetite_level, 'sleepiness_level': patient.sleepiness_level, 'insomnia_level': patient.insomnia_level}
	for level in current_health_condition_levels:
		total += int(current_health_condition_levels[level])
		if int(current_health_condition_levels[level]) >= 7:
			notify.send(user, recipient=user, verb='%s %s\'s %s is %s' % (patient.first_name, patient.last_name, level, current_health_condition_levels[level]), level='warning')
	if total >= 50:
		notify.send(user, recipient=user, verb='%s\'s health condition is urgent (Level: %s)' % (patient.get_full_name(), total), level='danger')


# class PatientProfileView(DetailView):
# 	model = Patient
# 	template_name = 'patients/patient_profile.html'

# 	def get_queryset(self):
# 		self.publisher = get_object_or_404(Publisher, name=self.args[0])
# 		return Book.objects.filter(publisher=self.publisher)

# 	def get_context_data(self, **kwargs):
# 		context = super(PatientProfileView, self).get_context_data(**kwargs)
# 		current_health_condition = {'nausea_level': self.patient.nausea_level, 'headache_level': self.patient.headache_level, 'sore_throat_level': self.patient.sore_throat_level, 'abdominal_pain_level': self.patient.abdominal_pain_level, 'constipation_level': self.patient.constipation_level, 'lack_of_appetite_level': self.patient.lack_of_appetite_level, 'sleepiness_level': self.patient.sleepiness_level, 'insomnia_level': self.patient.insomnia_level}
# 		context['current_health_condition'] = current_health_condition
# 		context['appointments'] = Appointment.objects.all()
# 		return context

def patientProfile(request, pk):
	patient = Patient.objects.get(pk=pk)
	allergies = patient.allergies.all()
	medical_history = patient.medical_background_information.all()
	current_health_condition = {'nausea_level': ['Nauseous', int(patient.nausea_level)], 
								'headache_level': ['Headache', int(patient.headache_level)], 
								'sore_throat_level': ['Sore throat', int(patient.sore_throat_level)], 
								'abdominal_pain_level': ['Abdominal pain', int(patient.abdominal_pain_level)], 
								'constipation_level': ['Constipated', int(patient.constipation_level)], 
								'lack_of_appetite_level': ['Lack of appetite', int(patient.lack_of_appetite_level)], 
								'sleepiness_level': ['Sleepy', int(patient.sleepiness_level)], 
								'insomnia_level': ['Insomnia', int(patient.insomnia_level)]
								}
	appointments = Appointment.objects.filter(patient=pk).order_by('date').reverse()
	prescriptions = Prescription.objects.filter(patient=pk).order_by('date').reverse()
	lab_reports = LabReport.objects.filter(patient=pk).order_by('request_date').reverse()
	records = Record.objects.filter(patient=pk).order_by('date_created').reverse()
	context = {'patient': patient, 'allergies': allergies, 
				'medical_history': medical_history, 
				'current_health_condition': current_health_condition,
				'appointments': appointments,
				'prescriptions': prescriptions,
				'lab_reports': lab_reports,
				'records': records
				}
	return render(request, 'patients/patient_profile.html', context)

class PatientSearchView(SearchView):
	template_name = 'search/search.html'
	queryset = SearchQuerySet()

src/patients/templates/patients/patient_appointments_panel.html
{% load i18n %}
{% load staticfiles %}
{% load ipims_tags %}
<div class="panel panel-default">
				<div class="panel-body">
					<h2>Appointments</h2>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Date</th>
										<th>Doctor</th>
										<th>Health Concern</th>
									</tr>
								</thead>
								<tbody>
									{% if appointments %}
									{% for appointment in appointments %}
									<tr class="clickable-row" data-href='/appointments/{{ appointment.pk }}'>
										<td> {{ appointment.date }}</td>
										<td> {{ appointment.doctor.get_full_name }} </td>
										<td> {{ appointment.health_condition }} </td>
									</tr>
									{% endfor %}
									{% else %}
									<tr><td>No appointments scheduled.</td></tr>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>

					{% if request.user|has_group:'staff' %}
					<div class="row">
						<div class="col-md-12">
							<a class="btn btn-default" href="/appointments/add/{{ patient.pk }}">Schedule Appointment</a>
							<a class="btn btn-danger" href="/appointments/emergency/{{ patient.pk }}">Emergency Room</a>
						</div>
					</div>
					{% endif %}

				</div>
			</div>

src/patients/templates/patients/patient_details_panel.html
{% load i18n %}
{% load staticfiles %}
{% load ipims_tags %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Details</h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-4 col-sm-4 col-xs-3">
							{% if patient.profile_picture %}
							<img src="{% static patient.profile_picture.url %}" class="img-thumbnail" /><br />
							{% else %}
							<img src="{% static '/static/images/default_avatar.jpg' %}" class="img-thumbnail" /><br />
							{% endif %}
						</div>
						<div class="col-md-8 col-sm-8 col-patient-info">
							<table class="table-patient-info">
								<tbody>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">DOB:</td>
										<td class="col-patient-info">{{ patient.dob }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Sex:</td>
										<td class="col-patient-info">{{ patient.get_sex_display }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Race/Ethnicity:</td>
										<td class="col-patient-info">{{ patient.get_ethnicity_display }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">SSN:</td>
										<td class="col-patient-info">{{ patient.get_ssn }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Phone:</td>
										<td class="col-patient-info">{{ patient.phone_number }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Email:</td>
										<td class="col-patient-info">{{ patient.email }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Insurance Provider:</td>
										<td class="col-patient-info">{{ patient.health_insurance_provider }}</td>
									</tr>
									<tr class="row-patient-info">
										<td class="col-patient-info-label">Insurance ID:</td>
										<td class="col-patient-info">{{ patient.health_insurance_id }}</td>
									</tr> <br/>
							</tbody>
							</table>

						</div>
					</div>
					<br />
					<div class="row">
						<div class="col-sm-12">
							<div class="row row-current-health-alerts">
								<div class="col-sm-12">
									{% for key, values in current_health_condition.items %}
										{% if values.1 >= 5 %}
										<span class="label 
										{% if values.1 >= 9 %} label-danger 
										{% elif values.1 >= 7 %} label-warning
										{% else %} label-default
										{% endif %}
										">{{ values.0 }}</span>
										{% endif %}
									{% endfor %}
								</div>
							</div>
							<div class="row row-current-health-buttons">
							<div class="col-sm-12">
								{% if request.user.is_authenticated %}
								{% if request.user|has_group:'doctor' or request.user|has_group:'nurse' %}
								<a class="btn btn-default btn-sm" href="health/">Update Health Status</a>
								{% endif %}
								{% endif %}
							</div>
						</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<ul class="list-group">
								<li class="list-group-item active">Allergies</li>
								{% if allergies %}
								{% for allergy in allergies %}
								<li class="list-group-item">{{ allergy }}</li>
								{% endfor %}
								{% else %}
								<li class="list-group-item">No known allergies.</li>
								{% endif %}
							</ul>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<ul class="list-group">
								<li class="list-group-item active">Medical History</li>
								{% if medical_history %}
								{% for medical_history_item in medical_history %}
								<li class="list-group-item">{{ medical_history_item }}</li>
								{% endfor %}
							</ul>
							{% else %}
							<li class="list-group-item">No medical history.</li>
							{% endif %}
						</div>
					</div>

					{% if request.user.is_authenticated %}
					{% if request.user|has_group:'doctor' or request.user|has_group:'nurse' or request.user|has_group:'staff' %}
					<a class="btn btn-default" href="update/">Update Patient Information</a><br/>
					{% endif %}
					{% endif %}

				</div>
			</div>

src/patients/templates/patients/patient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

<div class="row">
	<div class="col-md-7">
		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Patient Registration Form</h2>
				<form method='POST' action=''>
					{% csrf_token %}
					{{ form|crispy }}
					<input class = "btn btn-primary" type="submit" value="{% trans 'Submit' %}" />
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

src/patients/templates/patients/patient_lab_reports.html
{% load i18n %}
{% load staticfiles %}
{% load ipims_tags %}				
			<div class="panel panel-default">
				<div class="panel-body">
					<h2>Lab Reports</h2>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Request Date</th>
										<th>Lab Test</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									{% if lab_reports %}
									{% for lab_report in lab_reports %}
									<tr class="clickable-row" data-href='/labs/{{ lab_report.pk }}'>
										<td> {{ lab_report.request_date }}</td>
										<td> {{ lab_report.lab_test }} </td>
										<td> {{ lab_report.get_status_display }} </td>
									</tr>
									{% endfor %}
									{% else %}
									<tr><td>No lab report available.</td></tr>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>

					{% if request.user.is_authenticated and request.user|has_group:'doctor' %}
					<div class="row">
						<div class="col-md-12">
							<a class="btn btn-default" href="/labs/add/{{ patient.pk }}">Request Lab</a>
						</div>
					</div>
					{% endif %}

				</div>
			</div>

src/patients/templates/patients/patient_lab_reports_panel.html
{% load i18n %}
{% load staticfiles %}
{% load ipims_tags %}				
			<div class="panel panel-default">
				<div class="panel-body">
					<h2>Lab Reports</h2>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Request Date</th>
										<th>Lab Test</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									{% if lab_reports %}
									{% for lab_report in lab_reports %}
									<tr class="clickable-row" data-href='/labs/{{ lab_report.pk }}'>
										<td> {{ lab_report.request_date }}</td>
										<td> {{ lab_report.lab_test }} </td>
										<td> {{ lab_report.get_status_display }} </td>
									</tr>
									{% endfor %}
									{% else %}
									<tr><td>No lab report available.</td></tr>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>

					{% if request.user.is_authenticated and request.user|has_group:'doctor' %}
					<div class="row">
						<div class="col-md-12">
							<a class="btn btn-default" href="/labs/add/{{ patient.pk }}">Request Lab</a>
						</div>
					</div>
					{% endif %}

				</div>
			</div>

src/patients/templates/patients/patient_update_form.html
<!--Update Patient Health Conditions form-->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Update Patient Health Conditions</h2>
				<form method='POST' action='' enctype="multipart/form-data">
					{% csrf_token %}
					{{ form|crispy }}
					<div class="row">
						<div class="col-sm-8 col-sm-offset-2">
							<div class="panel panel-default">
								<div class="panel panel-body">
									<label>Nausea Level: <span id="id_visible_nausea_level"> {{ form.nausea_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="nausea_selector"></div>
										</div>
									</div>

									<label>Headache Level: <span id="id_visible_headache_level"> {{ form.headache_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="headache_selector"></div>
										</div>
									</div>

									<label>Sore Throat Level: <span id="id_visible_sore_throat_level"> {{ form.sore_throat_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="sore_throat_selector"></div>
										</div>
									</div>

									<label>Abdominal Pain Level: <span id="id_visible_abdominal_pain_level"> {{ form.abdominal_pain_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="abdominal_pain_selector"></div>
										</div>
									</div>

									<label>Constipation Level: <span id="id_visible_constipation_level"> {{ form.constipation_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="constipation_selector"></div>
										</div>
									</div>

									<label>Lack of Appetite Level: <span id="id_visible_lack_of_appetite_level"> {{ form.lack_of_appetite_level.value }} </span></label>
									<div class="row slider-row">
										<div class="col-md-11">
											<div id="lack_of_appetite_selector"></div>
										</div>
									</div>

									
								</div>
							</div>
							<input class = "btn btn-primary" type="submit" value="{% trans 'Submit' %}"/>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
</div>

<script>
	var values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	$("#nausea_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.nausea_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_nausea_level").val(values[ui.value]);
			$("#id_visible_nausea_level").text(values[ui.value]);
		}

	});

	$("#headache_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.headache_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_headache_level").val(values[ui.value]);
			$("#id_visible_headache_level").text(values[ui.value]);
		}

	});

	$("#sore_throat_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.sore_throat_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_sore_throat_level").val(values[ui.value]);
			$("#id_visible_sore_throat_level").text(values[ui.value]);
		}

	});

	$("#abdominal_pain_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.abdominal_pain_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_abdominal_pain_level").val(values[ui.value]);
			$("#id_visible_abdominal_pain_level").text(values[ui.value]);
		}

	});

	$("#constipation_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.constipation_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_constipation_level").val(values[ui.value]);
			$("#id_visible_constipation_level").text(values[ui.value]);
		}
	});

	$("#lack_of_appetite_selector").slider({
		animate: "fast",
		min: 0,
		max: values.length - 1,
		value: {{ form.lack_of_appetite_level.value }} - 1,
		slide: function(event, ui) {
			$("#id_lack_of_appetite_level").val(values[ui.value]);
			$("#id_visible_lack_of_appetite_level").text(values[ui.value]);
		}
	});
</script>
{% endblock %}