src/IPIMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
# Haystack Search
from haystack.forms import SearchForm
from haystack.views import SearchView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'default.views.home', name='home'),
    url(r'^dashboard/$', 'default.views.doctorDashboard', name='doctordashboard'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^patient/', include('patients.urls')),
    url(r'^search/', login_required(SearchView(form_class=SearchForm))),
    url(r'^appointments/', include('appointments.urls')),
    url(r'^inbox/notifications/', include('notifications.urls', namespace="notifications")),
    url(r'^prescriptions/', include('prescriptions.urls', namespace="prescriptions")),
    url(r'^stats/', 'stats.views.statisticalAnalysis'),
    url(r'^hc/', 'stats.views.plot'),
    url(r'^labs/', include('labreports.urls', namespace = "labreports")),
    url(r'^records/', include('records.urls', namespace="records")),
]

src/appointments/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from appointments import views

urlpatterns = [
	# Add Appointment
	url(r'^add/(?P<patient_pk>[0-9]+)/$', 
    	login_required(views.scheduleAppointment), name='schedule_appointment_form'),

	# Edit Appointment 
	url(r'^(?P<pk>[0-9]+)/edit', 
    	login_required(views.EditAppointment.as_view(success_url="/")), name='schedule_appointment_form'),

	# Add Emergency appointment
	url(r'^emergency/(?P<patient_pk>[0-9]+)/$', 
    	login_required(views.emergencyAppointment), name='emergency_form'),
	# Emergency notification sent successfully
	url(r'^emergency/success/(?P<pk>[0-9]+)/$', 
    	login_required(views.emergencyNotificationSent), name='emergency_notification_sent'),
	# Appointment Details
	url(r'^(?P<pk>[0-9]+)/$',
		login_required(views.AppointmentDetails.as_view()),name='appointment_details'),

	# Obsolete - AppointmentListView
	# url(r'^$', login_required(views.AppointmentListView.as_view()), name='appointment-list'),

	#Delete Patient 
	#SCHEDULED FOR REMOVAL - NOT USED
	url(r'^(?P<id>\d+)/delete', login_required(views.delete)),
]

src/appointments/models.py
from django.db import models
from patients.models import Patient
from django.contrib.auth.models import User
from smart_selects.db_fields import ChainedForeignKey

# Create your models here.
class Appointment(models.Model):
	""" Appointment model

	Dependencies: HealthCondition
	 """
	patient = models.ForeignKey(Patient)
	date = models.DateTimeField();
	health_condition = models.ForeignKey('HealthCondition')
	doctor = models.ForeignKey(User)
	def __str__(self):
		return str(self.pk)

class Emergency(models.Model):
	""" Emergency model

	Dependencies: HealthCondition
	"""
	patient = models.ForeignKey(Patient)
	date = models.DateTimeField();
	health_condition = models.ForeignKey('HealthCondition')
	doctor = models.ForeignKey(User)
	def __str__(self):
		return str(self.pk)


class HealthCondition(models.Model):
	""" HealthCondition model

	Links doctors to the specific health conditions that they treat.
	Used in Medical Records, as well.
	"""
	description = models.CharField(max_length = 64)
	doctors = models.ManyToManyField(User, blank=True)
	def __str__(self):
		return self.description

src/appointments/forms.py
from django.forms import ModelForm
from .models import HealthCondition, Appointment, Emergency
from django import forms
from django.contrib.auth.models import User
from default.widgets import UserFullnameChoiceField
from datetimewidget.widgets import DateTimeWidget

class ScheduleAppointmentForm(forms.Form):
	"""Form for scheduling appointments """
	def __init__(self, *args, **kwargs):
		super(ScheduleAppointmentForm, self).__init__(*args, **kwargs)
		# Set patient field to readonly. 
		self.fields['patient'].widget.attrs['readonly'] = True

	# Declare form fields
	patient = forms.CharField()
	date = forms.DateTimeField(widget=DateTimeWidget(attrs={'id':"yourdatetimeid"}, usel10n = True, bootstrap_version=3, 
													options= {
													'format': 'dd/mm/yyyy HH:ii P',
													'autoclose': True,
													'showMeridian' : True,
													'clearBtn': False
													}))
	health_condition = forms.ModelChoiceField(queryset=HealthCondition.objects.all())
	doctor = forms.ModelChoiceField(queryset=User.objects.all())

class EditAppointmentForm(ModelForm):
	"""Form for editing existing appointment """
	readonly_doctor = UserFullnameChoiceField(queryset=User.objects.all(), label="Doctor")
	class Meta:
		model = Appointment
		fields = 'patient', 'date', 'health_condition', 'doctor', 'readonly_doctor'
		widgets = {'patient': forms.HiddenInput(),
					'doctor': forms.HiddenInput(),
					'date': DateTimeWidget(attrs={'id':"yourdatetimeid"}, usel10n = True, bootstrap_version=3, 
													options= {
													'format': 'dd/mm/yyyy HH:ii P',
													'autoclose': True,
													'showMeridian' : True,
													'clearBtn': False
													})} # Hide patient form. 
	def __init__(self, *args, **kwargs):
		super(EditAppointmentForm, self).__init__(*args, **kwargs)
		instance = getattr(self, 'instance', None)
		self.fields['readonly_doctor'].initial = instance.doctor
		self.fields['doctor'].widget.attrs['disabled'] = 'disabled'
		self.fields['readonly_doctor'].widget.attrs['disabled'] = 'disabled' 
		self.fields['health_condition'].widget.attrs['disabled'] = 'disabled' 

class EmergencyForm(forms.Form):
	"""Form for alerting emergency room staff of incoming patient """

	# Declare form fields
	patient = forms.CharField()
	date = forms.DateTimeField(widget=forms.HiddenInput())
	health_condition = forms.ModelChoiceField(queryset=HealthCondition.objects.all())
	doctor = forms.ModelChoiceField(queryset=User.objects.all())

	def __init__(self, *args, **kwargs):
		super(EmergencyForm, self).__init__(*args, **kwargs)
		# Set patient field to readonly. 
		self.fields['patient'].widget.attrs['readonly'] = True

src/appointments/views.py
from django.shortcuts import render
from django.conf.urls import include, url
from django.views.generic import CreateView, UpdateView, DetailView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.utils import timezone
from django.contrib.auth.models import Group, User
from notifications import notify
import datetime

from .models import Appointment, Emergency, HealthCondition
from patients.models import Patient
from .forms import ScheduleAppointmentForm, EditAppointmentForm, EmergencyForm


def scheduleAppointment(request, patient_pk):
	"""View for scheduling a new appointment.

	Template: appointments/schedule_appointment_form.html
	Form: appointments/forms.py → ScheduleAppointmentForm()
	"""

	# Get health conditions to send in context for chained selection
	health_conditions = HealthCondition.objects.all()

	if request.method == 'POST':
		''' When the user clicks Submit '''
		# Load data from the form
		form = ScheduleAppointmentForm(request.POST)

		if form.is_valid():
			'''If the data from the form is valid, create a appointment object with the data from the fields.

			Redirect user to the details page for new appointment 
			'''
			patient_instance = Patient.objects.get(pk=patient_pk) # get patient object using the patient's primary key (from URL argument)
			p = Appointment.objects.create(
				patient=patient_instance, 
				date=form.cleaned_data['date'], 
				health_condition=HealthCondition.objects.get(pk = request.POST.get("health_condition", "")), # Sets health condition object using pk from health condition field
				doctor=form.cleaned_data['doctor'])
			return HttpResponseRedirect('/appointments/' + str(p.pk) )

		else:
			# If the form contains invalid fields, reload form with the same values and display errors.
			return render(request, 'appointments/schedule_appointment_form.html', {
				'form': form,
				'patient': Patient.objects.get(pk=patient_pk),
				'health_conditions': list(health_conditions),
				'health_conditions_count': int(health_conditions.count())
				})
			

	''' When form first loads '''
	# Generate initial field values (They're readonly, so can't be changed by user)
	data = {'patient': Patient.objects.get(pk=patient_pk), 
			'date': datetime.datetime.now()}
	# Create form
	form = ScheduleAppointmentForm(initial=data)

	# Display the Schedule Appointment form.
	return render(request, 'appointments/schedule_appointment_form.html', {
		'form': form,
		'patient': Patient.objects.get(pk=patient_pk),
		'health_conditions': list(health_conditions),
		'health_conditions_count': int(health_conditions.count())
	})

class EditAppointment(UpdateView):
	"""View for editing an existing appointment

	Template: appointments/edit_appointment_form.html
	Form: appointment/forms.py → EditAppointmentForm

	"""
	model = Appointment
	form_class = EditAppointmentForm
	template_name = 'appointments/edit_appointment_form.html'

	def form_valid(self, form):
		'''If the form fields are valid, update the Appointment model.

		Return to the Appointment 
		'''
		self.object = form.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		return reverse('appointment_details', kwargs={
			'pk': self.object.pk
			})

# class EmergencyAppointment(CreateView):
# 	""" View for Creating an Emergency appointment

# 	Model: Emergency
# 	Template: appointments/emergency_form.html
# 	Form: appointments/forms.py → EmergencyForm

# 	"""
# 	model = Emergency
# 	form_class = EmergencyForm
# 	template_name = 'appointments/emergency_form.html'

# 	def form_valid(self, form):
# 		'''If the form fields are valid, create Emergency model.

# 		Redirect user 

# 		'''
# 		self.object = form.save()
# 		return HttpResponseRedirect(self.get_success_url())

# 	def get_success_url(self):
# 		return '/appointments/' + str(self.object.pk)

def emergencyAppointment(request, patient_pk):
	"""View for alerting Emergency Room doctor of incoming patient.

	Template: appointments/emergency_form.html
	Form: appointments/forms.py → EmergencyForm()
	"""

	# Get health conditions to send in context for chained selection
	health_conditions = HealthCondition.objects.all()
	group = Group.objects.get(name='er_doctor')
	er_doctors = group.user_set.all()
	if request.method == 'POST':
		''' When the user clicks Submit '''
		# Load data from the form
		form = EmergencyForm(request.POST)

		if form.is_valid():
			'''If the data from the form is valid, create a appointment object with the data from the fields.

			Redirect user to the details page for new appointment 
			'''
			patient_instance = Patient.objects.get(pk=patient_pk) # get patient object using the patient's primary key (from URL argument)
			e = Emergency.objects.create(
				patient=patient_instance, 
				health_condition=HealthCondition.objects.get(pk = request.POST.get("health_condition", "")), # Sets health condition object using pk from health condition field
				date=form.cleaned_data['date'],
				doctor=form.cleaned_data['doctor'])
			notify.send(request.user, recipient=e.doctor, verb='New patient admitted to Emergency Room: %s due to %s!' % (e.patient.get_full_name_normalized(), e.health_condition), level='danger', target=e)
			return HttpResponseRedirect('/appointments/emergency/success/' + str(e.pk)) # FIX - SEND TO ALERT SUCCESS PAGE!

		else:
			# If the form contains invalid fields, reload form with the same values and display errors.
			return render(request, 'appointments/emergency_form.html', {
				'form': form,
				'patient': Patient.objects.get(pk=patient_pk),
				'health_conditions': list(health_conditions),
				'er_doctors': er_doctors
				})
			

	''' When form first loads '''
	# Generate initial field values (They're readonly, so can't be changed by user)
	data = {'patient': Patient.objects.get(pk=patient_pk), 'date': datetime.datetime.now()}
	# Create form
	form = EmergencyForm(initial=data)

	# Display the Schedule Appointment form.
	return render(request, 'appointments/emergency_form.html', {
		'form': form,
		'patient': Patient.objects.get(pk=patient_pk),
		'health_conditions': list(health_conditions),
		'er_doctors': er_doctors
	})

def emergencyNotificationSent(request, pk):
	return render(request, 'appointments/emergency_alert_sent.html', {'emergency': Emergency.objects.get(pk=pk)} )

class AppointmentDetails(DetailView):
	"""View for the Appointment Details

	Model: Appointment
	Template: appointmentments/details.html

	"""
	model = Appointment
	template_name = 'appointments/details.html'
	def get_context_data(self, **kwargs):
		context = super(AppointmentDetails, self).get_context_data(**kwargs)
		return context

""" OBSOLETE - Delete? """
# class AppointmentListView(ListView):

# 	model = Appointment

# 	def get_context_data(self, **kwargs):
# 		context = super(AppointmentListView, self).get_context_data(**kwargs)
# 		return context


def delete(request, id):
	""" Delete patient (pk = id)

	"""
	appointment = get_object_or_404(Appointment, pk=id)
	patient_id = appointment.patient.pk
	appointment.delete()
	return HttpResponseRedirect('/patient/' + str(patient_id))

src/appointments/templates/appointments/appointment_list.html
<!-- NO LONGER USED

-->
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<div class="row"><div class="col-md-8">
<div class="list-group">
  <div class="list-group-item active">
    Appointments
  </div>
  {% for appointment in object_list %}
  	<a href="{{ appointment.pk }}" class="list-group-item">{{ appointment.date.ctime }} {{ appointment.patient.last_name }}, {{ appointment.patient.first_name }}</a>
  {% empty %}
  	<li class="list-group-item">No appointments scheduled.</li>
  {% endfor %}
  </div></div></div>
  <div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
	<a class="btn btn-default" href="add/">Schedule Appointment</a>
	<a class="btn btn-danger" href="emergency/">Emergency Room</a>
  </div></div>
{% endblock %}

src/appointments/templates/appointments/details.html
{% extends "base.html" %}
{% load i18n %}
{% load ipims_tags %}
{% block content %}
<a class="btn btn-default" href="{% url 'patient_profile' appointment.patient.pk %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>  Back to Profile</a><p></p>
<div class="row">
<div class="col-sm-6">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Appointment Details</h3>
	  </div>
	  <div class="panel-body">
	    <b>Patient:</b> <a href="{% url 'patient_profile' appointment.patient.pk %}">{{ appointment.patient }}</a><br/>
	    <b>Date:</b> {{ appointment.date }}<br/>
	    <b>Health Condition:</b> {{ appointment.health_condition }}<br/>
	    <b>Doctor:</b> {{ appointment.doctor.get_full_name }}<br/>
	  </div>
	</div>

	{% if request.user.is_authenticated and request.user|has_group:'staff' %}
	<a class="btn btn-default" href="delete/">Cancel Appointment</a> <a class="btn btn-primary" href="edit/">Edit Appointment</a>
	{% endif %}

	</div>
</div>
{% endblock %}

src/appointments/templates/appointments/edit_appointment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load stat_tags %}
{% load ipims_tags %}

{% block content %}
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-body">

				<!-- HEADING -->
				<h2>Edit Appointment</h2>

				<!-- Create a readonly patient field.

				DO NOT IMPLEMENT THIS WAY. THIS WAS MY FIRST FORM AND I DIDN'T KNOW WHAT I WAS DOING ;) 
				The -->
				<div class="form-group"><label class="control-label">Patient</label>
					<div class="controls">
						{# Display Patient's Name (Read-only) #}
						<input class="form-control" name="patient" type="text" value="{{ form.instance.patient }}" disabled="true">
					</div>
				</div>
				<form method='POST' action=''>
					{% csrf_token %}
					{{ form|crispy }}
					<div class="row">
						<div class="col-md-7 col-sm-9 col-xs-5"></div>
						<div class="col-md-2 col-sm-1 col-xs-3">
							<a href="/appointments/{{ appointment.pk }}">Cancel</a>
						</div>
						<div class="col-md-2 col-sm-2" col-xs-2>
							<input class = "btn btn-primary" type="submit" value="{% trans 'Schedule' %}" />
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

src/appointments/templates/appointments/emergency_alert_sent.html
{% extends "base.html" %}
{% block content %}
<div class="row">
	<div class="col-xs-12">
		<div class="alert alert-success alert-danger-custom" role="alert">
			Emergency Room staff have been notified of {{ emergency.patient.get_full_name_normalized }}'s admittance.
		</div>
	</div>
</div>
<a class="btn btn-default" href="{% url 'patient_profile' emergency.patient.pk %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>  Back to Profile</a><p></p>
{% endblock %}

src/appointments/templates/appointments/emergency_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load stat_tags %}
{% load ipims_tags %}
{% block content %}

<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Alert Emergency Room</h1>
				<form method='POST' action=''>
					{% csrf_token %}
					{{ form|crispy }}
					<input class = "btn btn-danger" type="submit" value="{% trans 'Alert Emergency Room' %}" />
				</form>
			</div>
		</div>
	</div>
</div>


<script>
 	$(window).load(function() {
 		console.log("FIRED")
 		$option = $("<option></option>").attr("value", -1).text("Must select health condition first...")
 		$("#id_doctor").empty().attr("disabled", true).append($option);
 	});
	$("#id_health_condition").change(function() {
		$selected_health_condition = $("#id_health_condition option:selected").val() - 1;
		$option = $("<option></option>").attr("value", -1).text("---------");
		$("#id_doctor").empty().attr("disabled", false).append($option);
		{% if er_doctors %}
				{% for doctor in er_doctors %}
					console.log('{{ doctor }}')
					$option = $("<option></option>").attr("value", {{ doctor.pk }}).text("{{doctor.get_full_name}}")
					$("#id_doctor").append($option);
				{% endfor %}
		{% else %}
		console.log("ERROR: er_doctors = None.")
		{% endif %}
	});
</script>
{% endblock %}

src/appointments/templates/appointments/schedule_appointment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load ipims_tags %}
{% block content %}
{% load stat_tags %}

{% block extrahead %}
{{ form.media }}
{% endblock %}
<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Schedule Appointment</h2>
				<form method='POST' action=''>
					{% csrf_token %}
					{{ form|crispy }}
					<div class="pull-right" >
						<div class="row">
							<div class="col-md-4 col-xs-5">
								<a href="/patient/{{ patient.pk }}">Cancel</a>
							</div>
							<div class="col-md-2 col-xs-5">
								<input class = "btn btn-primary" type="submit" value="{% trans 'Schedule' %}" />
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
 	$(window).load(function() {
 		console.log("FIRED")
 		$option = $("<option></option>").attr("value", -1).text("Must select health condition first...")
 		$("#id_doctor").empty().attr("disabled", true).append($option);
 	});
	$("#id_health_condition").change(function() {
		$selected_health_condition = $("#id_health_condition option:selected").val() - 1;
		$option = $("<option></option>").attr("value", -1).text("---------");
		$("#id_doctor").empty().attr("disabled", false).append($option);
		{% if health_conditions_count %}
		{% for i in health_conditions_count|get_range %}
			if($selected_health_condition == {{ i }}){
				{% with h=health_conditions|lookup:i %}
				{% for doctor in h.doctors.all %}
					console.log('{{ doctor }}')
					$option = $("<option></option>").attr("value", {{ doctor.pk }}).text("{{doctor.get_full_name}}")
					$("#id_doctor").append($option);
				{% endfor %}
				{% endwith %}
			}
		{% endfor %}
		{% endif %}
	});
</script>
{% endblock %}